### ISSUE TITLE
全般 Cocos2d-x 3.10へのご対応／動作保証につきまして

### ISSUE THREAD

**Issue by nishimotohideki** [SpriteStudio/SS5PlayerForCocos2d-x#40]
いつもお世話になっております。
下記、要望となります。

現在、Cocos2d-x 3.8.1（JSを使用）をベースに、キャラのアニメーションにSpriteStudioを使わせていただいて、ゲームを開発しております。
ですが、リソースマネージャ等の都合で、Cocos2d-xのバージョンを3.8.1→3.10にあげてリリースする予定です。
なお、Cocos2d-x 3.10は未リリースですが、当方のエンジニアで開発状況を鑑みて近々のリリースとの判断で動いております。
下記ご参考までに。
https://trello.com/b/Np6obnuE/cocos2d-x-roadmap
https://github.com/cocos2d/cocos2d-x/commits/v3.10

そこで、SpriteStudioのCocos2d-x 3.10へのご対応／動作保証もいただけると大変ありがたく、要望として挙げさせていただきます。
すでにご準備されていましたら恐縮です。

・当方はJSで開発しておりますので、JSB周りのご確認いただけると嬉しいです。

また、当方の都合で恐縮ですが、コードフリーズを1月末に予定しているため、それまでに動作保証があると大変ありがたかったりはします…。
以上、よろしくお願い致します。

**Comment by DKAlpha** [comment]
要望ありがとうございます。
SS5PlayerForCocos2d-xの対応方針についてご説明させていただきます。
こちらはWikiにも記述があります通り、正式リリース版が公開されてから随時対応していくという方針でアップデートを行っております。
現状ではCocos2d-x3.9での動作検証をこれから行う予定になっております。
Cocos2d-x3.10の対応は3.10の正式リリース後にスケジュールをみて対応する形となります。
現状でございますと年末年始を挟むこともあり、ご要望にありました1月末まで対応できるかは未定となっております事をご了承ください。
また動作保証という事を書かれておりますが、もちろん不具合等可能な限り対応したいと考えておりますが、こちらのプレイヤーはMITライセンスで提供しておりまして、発生した損害に対する責任は負わない形で公開している物となります。
お手数ではございますが[ライセンス](https://github.com/SpriteStudio/SS5PlayerForCocos2d-x/blob/master/LICENSE)をお確かめの上ご使用いただければと思います。

**Comment by nishimotohideki** [comment]
こちら早速のご回答ありがとうございました！
ドキュメントの読み込み不足しており申し訳ないです。
3.10正式リリース後のご対応となること、また、MITライセンスであることについても、承知しました。
今後とも何卒よろしくお願い致します。
