### ISSUE TITLE
WebGLでレンダリングされるjavascriptのプレイヤー実装予定はありますか？

### ISSUE THREAD

**Issue by ghost** [SpriteStudio/SS5PlayerForCocos2d-x#55]
質問させていただきます。
Cocos2d-x v3を利用してjavascriptでコーディングしてwebにpublishしております。

SpriteStudio5で作成したアニメーションを是非webでの動作させたいと思っているのですが、SpriteStduio5で作成されたアニメーションデータを、Cocos2d-xのWebGLレンダリングで動作させるためのjavascriptプレイヤーの実装予定はございますでしょうか？

**Comment by DKAlpha** [comment]
問い合わせいただきました、cocos2d-xのjavascript向けSS5Playerについてですが、現状では提供の予定はございません。

補足ですが、過去にSS5PlayerForCocos2d-xのjavascriptラッパーを作成し利用するような試みをされているという話を聞いた事もありますので、つなぎの部分を作成すれば利用する事は可能ではないかと思われます。

もう一つ、javascriptという事で、もしかするとこちらのSs5ConverterToSSAJSONが参考になるかもしれません。
https://github.com/SpriteStudio/Ss5ConverterToSSAJSON/wiki
これはSpriteStudioのアニメーションをJSON形式にコンバートするコンバータですが、HTML5＋javascriptで再生するサンプルも含まれておりますので、こちらが参考になるかもしれません。

**Comment by ghost** [comment]
ご回答いただきありがとうございます。
現状、予定がないこと承知いたしました。
また、Ss5ConverterToSSAJSONの情報を提供いただきありがとうございました。
参考にさせていただきます。
