### ISSUE TITLE
乗算や加算合成をspritestudioで設定しても反映されない

### ISSUE THREAD

**Issue by Ryuma-Hachisu** [SpriteStudio/SS5PlayerForCocos2d-x#59]
乗算や加算合成をspritestudioで設定しても反映されないのですがどうすればよいでしょうか？

**Comment by DKAlpha** [comment]
参考までに、使用しているcocos2d-xのバージョンとSS5PlayerForCocos2d-xのバージョンをお教えいただいてもよろしいでしょうか？

**Comment by Ryuma-Hachisu** [comment]
すいません、こちらに関しては調査不足だったみたいです。
