### ISSUE TITLE
changeTextureの引数について

### ISSUE THREAD

**Issue by ghost** [SpriteStudio/SS5PlayerForCocos2d-x#6]
細かい話で申し訳ないのですが、Cocos2d-x_v3のchangeTexture(SS5Player.h)の引数のcallNameはssceの名前を指定するため、引数名がcellNameの解釈で宜しいでしょうか?
宜しくお願い致します。

**Comment by DKAlpha** [comment]
報告ありがとうございます。
ご指摘の通りcellNameの誤字になります。
拡張子を除いたssce名を指定してください。

**Comment by ghost** [comment]
回答いただきどうもありがとうございます。拡張子を除いたssce名を指定して使用させていただきます。
